spring:
  application:
    name: "demo for implementation of spring security and jwt in spring boot application"

server:
  port: 8080
  servlet:
    context-path: "/api"

logging:
  level:
    org.springframework.*: TRACE
